### ISSUE TITLE
Log In GUI Error - fbsetbg: I can't find an app to set the wallpaper with

### ISSUE THREAD

**Issue by osalbahr** [BlackArch/blackarch-installer#86] opened 2023-03-19 07:00 UTC
# Error

Upon logging in, I get the following error.

From `xmessage`:
> fbsetbg: I can't find an app to set the wallpaper with. You can install one in many ways but i will give you some simple advice: install Eterm and you're set. Eterm provides Esetroot and thats a great wallpaper setter. I recommend you install the package provided by your distro.

How can I bypass this error and arrive at the default wallpaper?

![image](https://user-images.githubusercontent.com/54853250/226156208-3a7b0be3-88d4-4106-9fcf-0c9df2bbfc53.png)

This is the window right before it:
![image](https://user-images.githubusercontent.com/54853250/226156236-d1a9e167-9f8a-4dc0-b46e-1c8869cfbf62.png)

The same happens if I log in as root. And I tried to reinstall BlackArch as another VM and I was able to replicate the same error. In both instances, I kept the default configurations.

![Screen Shot 2023-03-19 at 1 59 41 AM](https://user-images.githubusercontent.com/54853250/226156591-65c0e448-7ff2-4b38-b709-8c4b4921cbfb.png)

# Attempts

The only place I have found this error with BlackArch is BlackArch/blackarch-site#91 and @PedroSFreitas mentioned something about changing a line in `blackarch-config-x11`. I don't know if the temporary fix is still applicable since the issue was closed by @noptrix about 5 years ago. If so, how can I apply the fix? I am unsure as when I arrive at the error I do not see a terminal.

Clicking `fn+control+option+command` launches a terminal with no internet connection, so I couldn't apply the fix in Newbie Corner - Arch Linux Forumseither:
[fbsetbg problem - https://bbs.archlinux.org/viewtopic.php?id=79984](https://bbs.archlinux.org/viewtopic.php?id=79984).

![image](https://user-images.githubusercontent.com/54853250/226158520-970a5d1e-6b7e-492b-9ea5-a34adf0a870e.png)

# Install

I used the BlackArch Linux 64 bit Netinstall ISO version 2021.09.01 (the latest) and followed the [installation guide](https://blackarch.org/blackarch-install.html) to install in VirtualBox, with the only modification being the following network workaround by @ikstream:

              Please run `pacman -Syy archlinux-keyring blackarch-keyring` before running the installer

_Originally posted by @ikstream in https://github.com/BlackArch/blackarch/issues/2872#issuecomment-1042601111_
 
 As was applied in [BlackArch NetInstall + i3wm (chroot error!)](https://youtu.be/RYZUpL5blmw?t=956).
 
 (this is the same issue that was closed in #73 and #74)
 
 ```console
$ openssl sha1 blackarch-linux-netinst-2021.09.01-x86_64.iso
SHA1(blackarch-linux-netinst-2021.09.01-x86_64.iso)= 9fcde13d1abb191642d66fd60d45c00e3f46ee66
```

**Comment by ikstream** [comment] 2023-03-19 14:40
There will be an ISO release on 01 April 2023 we will see if we can reproduce and fix this issue you are facing. The installer is currently checked prior to the release.

**Comment by anunna** [comment] 2023-10-18 12:14
Closing because it focuses on a 2 year old ISO. Please use [blackarch-linux-netinst-2023.04.01-x86_64](https://ftp.halifax.rwth-aachen.de/blackarch/iso/blackarch-linux-netinst-2023.04.01-x86_64.iso). If you have the same issue on the current version, please open the issue again.

**Closed as completed by anunna** 2023-10-18 12:14 UTC
Labels: bug
