### ISSUE TITLE
Login Stuck

### ISSUE THREAD

**Issue by byronrogersjr** [BlackArch/blackarch-installer#62] opened 2020-07-04 21:06 UTC
I was on the last step of my blackarch install, and my computer lost power. When I booted the computer back up, it came up with Blackarch...I entered my password, and then I got "/dev/mapper/r00t: clean, 58225/4825088 files, 1038290/19274262 blocks" with a blinking cursor below, and it doesn't go any further. When I try to rerun the install, it gives me "probing edd (edd=off to disable)" says bios error, and goes no further... What is happening? Can anybody help me get my blackarch up and running? Thanks in advance.

**Comment by ikstream** [comment] 2020-07-05 07:50
Did it loose power during package installation?
Does it only show 'Bios error' or are there more information present?
Have you an USB stick or sd card connected during startup?
Can you boot from USB stick and `chroot` into your installed system?

**Comment by byronrogersjr** [comment] 2020-07-05 20:25
I was able to re-install, got through install completely and successfully,
but when I boot up I get
"Starting version 245.6-8-arch

A password is required to access the r00t volume:
Enter passphrase for /dev/sda3:"
Once I enter my password, I get "/dev/mapper/r00t: clean, 1456761/4825088
files, 18206416/19274262 blocks" and it does nothing from there...despite a
complete and successful install...btw...if you can't tell already, I'm a
total *n00b* I just want to get this Linux on this computer for
cybersecurity/CEH/CPT prep/sandbox purposes. I hope you can help me out.
Thank you.

Regards,
Byron Rogers, Jr.

**Comment by ikstream** [comment] 2020-07-06 07:18
This looks like something went wrong during installation. Did you use the live iso, or the netinstall? 
What did you use for disk layout? swap/root/home

Can you please boot from usb and manually open your encrypted root partition (`cryptsetup open /dev/sda3 r00t`), mount it (`mount /dev/mapper/r00t /mnt`) and paste the content of `/mnt/etc/fstab`.

**Comment by ikstream** [comment] 2020-07-06 07:47
And please add the content of  the `HOOKS` line in `/mnt/etc/mkinitcpio.conf`

**Comment by byronrogersjr** [comment] 2020-07-06 10:25
So I went on and installed full ArchLinux onto my PC. I haven't pushed
BlackArch yet, but now that I have Arch, I'm hoping it would be more
seamless. I'll keep you posted. Thanks for the help so far!

Regards,
Byron Rogers, Jr.

**Comment by ikstream** [comment] 2020-07-06 18:44
As we can't debug the initial problems any longer, I am going to close this issue. If you encounter any errors, feel free to comment here, or join us on irc/discord and ask there for additional help.

**Closed as completed by ikstream** 2020-07-06 18:44 UTC

**Comment by Edu4rdSHL** [comment] 2020-07-06 19:09
Additionally, please use the develop version of the installer and see if you can still reproduce the issue. See https://github.com/BlackArch/blackarch-installer/tree/develop#using-the-git-version
